[package]
name = "week2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "freq"
path = "src/freq.rs"

[[bin]]
name = "coins"
path = "src/coins.rs"